### ISSUE TITLE
Help with Arch/Configuration with Apps in Multiple namespaces

### ISSUE THREAD

**Issue by linuxbsdfreak** [abhirockzz/kubernetes-keda-prometheus#2]
Hi @abhirockzz . 

I was following the link. Nice work with KEDA

https://itnext.io/tutorial-auto-scale-your-kubernetes-apps-with-prometheus-and-keda-c6ea460e4642

and it works as expected.   For testing i have installed all the components in a single namespaces along with the keda operator from helm charts.
 
I have the following Qs:

- How does it work for different apps running in multiple namespaces and sharing a single prometheus instance in the cluster? 
- Could you provide me some architecture insights along with the configuration for the same?

I understand that there will be a different scaled object configuration for each app in the relevant namespace. 

Thanks for your help.

Regards,
Kevin

**Comment by abhirockzz** [comment]
Yes. You will need to reference a `Deployment` in the `ScaledObject` configuration - this is 1:1 relation. Also, both need to be in the same namespace. You might find the spec handy - https://keda.sh/concepts/scaling-deployments/#scaledobject-spec

Let me know if you have any specific Qs as far as the architecture is concerned.

Glad you were able to get this up and running!

**Comment by linuxbsdfreak** [comment]
Hi @abhirockzz,

Thanks for the feedback. I have the following  Qs.

- How does one mitigate the SIGTERM from Kubernetes for the deployement?
-  What changes have to be done in the app? - Do you have any sample example for the same?

If I have a single Prometheus instance for the K8s cluster and have different apps running in different namespaces.

- What changes do I need to do so that the scaler reacts to the correct metrics on Prometheus ? 
- Do you have a sample with 2 apps in running in different namespaces connecting a common Prometheus?
- Recommended Production Arch/config would be nice to have 

Regards,
Kevin

**Comment by linuxbsdfreak** [comment]
@abhirockzz . Could you provide me some feedback ? 

Kevin

**Comment by tomkerkhove** [comment]
- SIGTERM can't be avoided AFAIK - It's best to gracefully shutdown and make your app aware of that
- Your app does not have to change, you just add the autoscaling next to it which is what makes KEDA great (in my opinion at least)
- Having 2 apps connecting to the same Prometheus will just be 2 ScaledObjects that you deploy, each targetting a different deployment
- No changes required for scaler to react on metric, just configure the correct Promtheus trigger https://keda.sh/scalers/prometheus/

**Comment by linuxbsdfreak** [comment]
ok thx @tomkerkhove
